# Generated by Django 5.2.14 on 2026-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fusion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
